
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/auction_db"
    username: root
    password: "010603"
  data:
    redis:
      host: localhost
      port: 6379

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "${VNPAY_TMN_CODE}"
    hashSecret: "${VNPAY_HASH_SECRET}"
    returnUrl: "http://localhost:5173/payment-result"
    transactionUrl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"


